<?php


/**
 * Skeleton subclass for performing query and update operations on the 'timeline' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jan  2 11:31:53 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TimelinePeer extends BaseTimelinePeer {

} // TimelinePeer
