<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2012/01/02 11:47:45
return array(

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sfmixer' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropel' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfpropelbehavior' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropeldata' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropeldatabaseschema' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropelmanytomany' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropelpager' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropelbehaviorbase' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviori18n' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviori18ntranslation' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfony' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfpropelbehaviorsymfonybehaviors' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviortimestampable' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropeldatabase' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfwebdebugpanelpropel' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfformfilterpropel' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfpropelformfiltergenerator' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelformgenerator' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropellogger' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'swift_propelspool' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropelroute' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfphing' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfphinglistener' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelbasetask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildallloadtask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildalltask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelbuildfilterstask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildformstask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelbuildmodeltask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfpropelbuildschematask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelbuildsqltask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbuildtask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropelconfiguredatabasetask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropeldatadumptask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropeldataloadtask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelgenerateadmintask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelgeneratemoduletask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelgraphviztask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelinsertsqltask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelschematoxmltask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelschematoymltask' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sftesterpropel' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfvalidatorpropelchoice' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfwidgetformpropelchoice' => '/Users/robbymillsap/Source/symfony-1.4.8/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',

  // project
  'baseaction' => '/Users/robbymillsap/Sites/missionsolutions/lib/BaseAction.php',
  'basecomponent' => '/Users/robbymillsap/Sites/missionsolutions/lib/BaseComponent.class.php',
  'basemodel' => '/Users/robbymillsap/Sites/missionsolutions/lib/BaseModel.class.php',
  'baseform' => '/Users/robbymillsap/Sites/missionsolutions/lib/form/BaseForm.class.php',

  // project_model
  'timelinetablemap' => '/Users/robbymillsap/Sites/missionsolutions/lib/model/map/TimelineTableMap.php',
  'usertablemap' => '/Users/robbymillsap/Sites/missionsolutions/lib/model/map/UserTableMap.php',
  'basetimeline' => '/Users/robbymillsap/Sites/missionsolutions/lib/model/om/BaseTimeline.php',
  'basetimelinepeer' => '/Users/robbymillsap/Sites/missionsolutions/lib/model/om/BaseTimelinePeer.php',
  'baseuser' => '/Users/robbymillsap/Sites/missionsolutions/lib/model/om/BaseUser.php',
  'baseuserpeer' => '/Users/robbymillsap/Sites/missionsolutions/lib/model/om/BaseUserPeer.php',
  'timeline' => '/Users/robbymillsap/Sites/missionsolutions/lib/model/Timeline.php',
  'timelinepeer' => '/Users/robbymillsap/Sites/missionsolutions/lib/model/TimelinePeer.php',
  'user' => '/Users/robbymillsap/Sites/missionsolutions/lib/model/User.php',
  'userpeer' => '/Users/robbymillsap/Sites/missionsolutions/lib/model/UserPeer.php',

  // application
  'myuser' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/lib/myUser.class.php',

  // modules
  'timelineactions' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/timeline/actions/actions.class.php',
  'timelinecomponents' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/timeline/actions/components.class.php',
  'timelinedao' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/timeline/lib/TimelineDAO.class.php',
  'timelinemodel' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/timeline/lib/TimelineModel.class.php',
  'useractions' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/user/actions/actions.class.php',
  'usercomponents' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/user/actions/components.class.php',
  'userdao' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/user/lib/UserDAO.class.php',
  'usermodel' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/user/lib/UserModel.class.php',

  // frontend_modules
  'timelineactions' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/timeline/actions/actions.class.php',
  'timelinecomponents' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/timeline/actions/components.class.php',
  'timelinedao' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/timeline/lib/TimelineDAO.class.php',
  'timelinemodel' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/timeline/lib/TimelineModel.class.php',
  'useractions' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/user/actions/actions.class.php',
  'usercomponents' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/user/actions/components.class.php',
  'userdao' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/user/lib/UserDAO.class.php',
  'usermodel' => '/Users/robbymillsap/Sites/missionsolutions/apps/frontend/modules/user/lib/UserModel.class.php',

  // plugins_lib

  // plugins_module_lib
);
