<?php
// auto-generated by sfViewConfigHandler
// date: 2012/01/02 13:14:16
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'json_get_ticksSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'json_get_ticksSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == '' ? false : ''.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css', '', array ());
  $response->addStylesheet('blueprint/screen.css', '', array ());
  $response->addStylesheet('timeline.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js', '', array ());
  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css', '', array ());
  $response->addStylesheet('blueprint/screen.css', '', array ());
  $response->addStylesheet('timeline.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js', '', array ());
  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js', '', array ());
}

